apiVersion: v1
kind: PersistentVolume
metadata:
  name: shared-report-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/tmp/k8s-report"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: shared-report-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  volumeName: shared-report-pv   # 👈 explicitly bind to PV
  storageClassName: ""           # 👈 disable dynamic provisioning
